server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://moviedb-akash.c918bifp8fik.us-west-2.rds.amazonaws.com
    username: root
    password: password123
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
 
application:
  jwt:
    secret-key: 76397924423F4528482B4D6251655468576D5A7134743777217A25432A46294A